"""NeMo Guardrails config generator for RemediAX Agent 2 — Remediator.

Converts a batch of findings into a NeMo Guardrails ``config.yml`` file that
users can drop into any NeMo Guardrails deployment.  This is a pure config
generator — it does not run any NeMo runtime pipeline.

Import guard: raises ``ImportError`` when ``nemoguardrails`` is not installed.
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Any

import yaml

logger = logging.getLogger(__name__)


# Maps each OWASP LLM category to a pair (input_rail, output_rail).
# None means no rail is generated for that side.
_CATEGORY_TO_RAILS: dict[str, tuple[str | None, str | None]] = {
    "LLM01": ("llm01 prompt injection check", None),
    "LLM02": (None, "llm02 pii redaction"),
    "LLM03": ("llm03 supply chain check", None),
    "LLM04": ("llm04 data poisoning check", None),
    "LLM05": ("llm05 code injection check", "llm05 code output check"),
    "LLM06": (None, "llm06 tool misuse detection"),
    "LLM07": ("llm07 system prompt protection", "llm07 prompt leak detection"),
    "LLM08": ("llm08 vector poisoning check", None),
    "LLM09": (None, "llm09 hallucination check"),
    "LLM10": ("llm10 rate limit enforcement", "llm10 cascade detection"),
}


class NemoRunner:
    """Generate a NeMo Guardrails config.yml from a batch of findings.

    The generated YAML is a valid NeMo Guardrails ``config.yml`` that declares
    input and output rails for every OWASP category present in the findings.
    Users extend it with actual Colang flow definitions in ``.co`` files.

    Raises:
        ImportError: When ``nemoguardrails`` is not installed.
    """

    def __init__(self) -> None:
        self._ensure_installed()

    # ------------------------------------------------------------------ #
    #  Public API                                                          #
    # ------------------------------------------------------------------ #

    def generate_config(self, findings: list[Any]) -> str:
        """Generate a NeMo Guardrails config YAML string from findings.

        Args:
            findings: List of ``Finding`` objects (any object with
                      ``owasp_llm_category`` attribute).

        Returns:
            A YAML string suitable for use as NeMo Guardrails ``config.yml``.
        """
        categories = sorted({
            f.owasp_llm_category
            for f in findings
            if f.owasp_llm_category
        })

        input_flows: list[str] = []
        output_flows: list[str] = []

        for cat in categories:
            rails = _CATEGORY_TO_RAILS.get(cat)
            if rails is None:
                continue
            in_rail, out_rail = rails
            if in_rail and in_rail not in input_flows:
                input_flows.append(in_rail)
            if out_rail and out_rail not in output_flows:
                output_flows.append(out_rail)

        config: dict[str, Any] = {
            "models": [],
            "rails": {
                "input": {"flows": input_flows},
                "output": {"flows": output_flows},
            },
        }

        header = (
            "# NeMo Guardrails config — auto-generated by RemediAX\n"
            f"# Based on {len(findings)} finding(s) across: {', '.join(categories)}\n"
            "# Extend with Colang flow definitions in .co files\n"
        )

        logger.info(
            "NemoRunner: generated config with %d input rails and %d output rails "
            "covering %d categories",
            len(input_flows),
            len(output_flows),
            len(categories),
        )

        return header + yaml.safe_dump(config, default_flow_style=False, sort_keys=False)

    def save_config(self, config_str: str, path: str | Path) -> Path:
        """Write the config string to disk.

        Args:
            config_str: The YAML string returned by ``generate_config()``.
            path: Destination file path.

        Returns:
            The resolved ``Path`` that was written.
        """
        dest = Path(path)
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(config_str, encoding="utf-8")
        logger.info("NemoRunner: wrote NeMo config to %s", dest)
        return dest

    # ------------------------------------------------------------------ #
    #  Private helpers                                                     #
    # ------------------------------------------------------------------ #

    @staticmethod
    def _ensure_installed() -> None:
        try:
            import nemoguardrails  # noqa: F401
        except ImportError as exc:
            raise ImportError(
                "nemoguardrails is not installed. Install it with: pip install nemoguardrails"
            ) from exc
